package com.teltronic.app112.classes.enums

enum class IntCodes(val code:Int) {
    CODE_PERMISSION_CALL_PHONE(100),
    CODE_PERMISSION_FINE_LOCATION_FROM_MAIN_FRAGMENT_TO_LOCATION(200),
    CODE_PERMISSION_FINE_LOCATION_FROM_CONFIRM_FRAGMENT(201),
    CODE_PERMISSION_FINE_LOCATION_FROM_MAIN_FRAGMENT_TO_NEW_CHAT(202),
    CODE_PERMISSION_FINE_LOCATION_FROM_MAIN_ACTIVITY_TO_CONFIGURATION(203),
    CODE_REQUEST_GOOGLE_AUTH_MAIN(300),
    CODE_REQUEST_GOOGLE_AUTH_EDIT_PROFILE(400),
    CODE_REQUEST_API_PEOPLE_GOOGLE_AUTH_FRAGMENT_PROFILE(500),
    CODE_PERMISSION_CAMERA(600),
    CODE_PERMISSION_WRITE_EXTERNAL_STORAGE(700),
    CODE_PERMISSION_READ_EXTERNAL_STORAGE(800),
    CODE_PHOTO(900)
}